### ISSUE TITLE
Can comments occur after top-level object?

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#12]
There are surprisingly few restrictions on where comments can appear, e.g., this is legit:

```
$ echo 'c1 { a = /* c1 */ 1 /* c2 */]' |./enctool convert -df cte
c0
{
    a = /* c1 */
    1
    /* c2 */
}
```

However, if you put a comment after the top-level object, it's simply ignored:

```
$ echo 'c1 /* c1 */ 345 /* c2 */' |./enctool convert -df cte
c0
/* c1 */
345
```

More generally, I've seen a couple cases where the parser stops parsing before the end of the file.  It would be a great safety check for the parser to make sure that, when it thinks it's at the end of parsing, that there's no more (non-whitespace) data in the file.

**Comment by kstenerud** [comment]
Actually, deterministic document end is an intentional feature of CTE and CBE, such that any envelope format leveraging it for complext data representation doesn't require its own end-of-field detection or byte stuffing / character escape format.

As an example, consider if an INI file reader were to incorporate CTE to leverage it for more complex data representation:

```
[section]
instance = rows
data = c1 [
    1
    2
    3
]
time = c1 2020-01-01/12:42:59/Europe/Berlin
blah = blah
```
The INI parser could keep its existing "data ends on EOL" parsing, but also support format detection to detect a CTE document (denoted by `c1 `). When it encounters this, it switches to CTE parsing, which reads from the stream until it detects the end of the top-level object. It then returns control to the INI parsing routines, which see an EOL like always and continue on as if nothing happened.

Of course this means that in a construct like `c1 /* comment 1 */ abcd /* comment 2 */`, the document would end before "comment 2". It would be up to the application to decide whether that's an error or not (maybe the text `/* comment 2 */` is part of some other encoded data?)

But in this case it would be a faulty document since enctool expects a complete document with no extraneous data, so it's a legitimate bug :)

Edit: Or maybe I could instead add a feature "scan this stream and extract the nth document you see". In default mode, it's strict about no extraneous data, but in scan mode it allows it.

**Comment by kengruven** [comment]
Oh, I see.

I agree with having "enctool" either scan the entire file/stream and require exactly 1 document, or add an option to extract document N from the stream.  Both good options.

The root cause here was that I was trying to figure out the valid places to put a comment by trial-and-error.  I see (in the structural spec) notes restricting them in Markup, Marker, Typed Arrays, and Concatenation, but no other mention of where they can exist.  (I would not have guessed that they can occur before the top level object, but not after it, for example.)  So a note about this case would be nice.

**Comment by kstenerud** [comment]
Comments are [pseudo-objects](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#pseudo-objects), so they are valid any place a real object can be placed (with some additional restrictions in the case of concatenation, typed arrays, etc). I'll have to tighten up that part of the spec to make it more clear.

But to your examples:

```
c1 /* c1 */ 345 /* c2 */
```
In this case, a second object cannot be placed after the top-level object, so the second comment is illegal. Also, since the document officially ends after the top-level object (`345`) is complete, it stops processing.

```
$ echo 'c1 { a = /* c1 */ 1 /* c2 */]' |./enctool convert -df cte
c0
{
    a = /* c1 */
    1
    /* c2 */
}
```
This looks a little weird because I've got the comment printer set to automatically go to a new line after a comment. It's hard to decide upon a policy for this, because for longer lines it looks ugly the other way:

```
c0
{
    a-key-of-some-sort = /* A comment that is starting to get a bit on the long side */ "This is the value associated with a-key-of-some-sort"
}
```
```
c0
{
    a-key-of-some-sort = /* A comment that is starting to get a bit on the long side */
    "This is the value associated with a-key-of-some-sort"
}
```
Also, it's not common to comment the value of a k-v pair; usually you'd comment the key:

```
c0
{
    /* A comment that is starting to get a bit on the long side */
    a-key-of-some-sort = "This is the value associated with a-key-of-some-sort"
}
```

**Comment by kengruven** [comment]
Oh, I missed the "must not appear after the top-level object" line for pseudo-objects.  That would indeed explain this restriction.  Thanks.

I agree that pretty-printing is a hard problem (especially with comments), and I'm not too concerned with getting it right in every case.
