### ISSUE TITLE
Comment example fails to parse

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#13]
The [CTE spec has a sophisticated comment example](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#comment).  Unfortunately, it doesn't parse:

```
$ cat | ./enctool convert -df cbe | hexdump -C
c1
// Comment before top level object
{
    // Comment before the "name" object.
    // And another comment.
    "name" = "Joe Average" // Comment after the "Joe Average" object.

    "email" = // Comment after the "email" key.
    /* Multiline comment with nested comment inside
      |r mailto:joe@average.org|
      /* Unlike in C, nested multiline
         comments are allowed */
    */
    |r mailto:someone@somewhere.com|

    "data" // Comment after data
    =
    // Comment before some binary data (but not inside it)
    |u8x 01 02 03 04 05 06 07 08 09 0a|
}
offset 442 (line 16, col 14): Expected map separator (=) but got [/]
```

Maps seem to support comments at every position except right before a `=`:

```
$ echo 'c1 { /* c1 */ a /* c2 */ = /* c3 */ 1 /* c4 */ }' |./enctool convert -df cte
c0
{
    /* c1 */
    offset 17 (line 1, col 18): Expected map separator (=) but got [*]
$ echo 'c1 { /* c1 */ a = /* c3 */ 1 /* c4 */ }' |./enctool convert -df cte
c0
{
    /* c1 */
    a = /* c3 */
    1
    /* c4 */
}
```

**Comment by kengruven** [comment]
Looking at this again today, I think that the implementation matches the spirit of the spec, and the spec is just a bit vague.  The CTE syntax doesn't visually/explicitly connect a Comment with its target, but that seems to be the intent:

> "[Comments] tend to unofficially refer to what follows in the document, similar to how comments are used in source code."

(Aside: I don't think the latter half of that sentence is quite accurate.  That ordering is usually true of block comments, but with inline comments [like `// Comment after the "Joe Average" object.` or `// Comment after data`], it's the opposite.)

So you can't put a comment immediately before a `=` because `=` isn't an object.  This also explains why you can't put a comment after the document's root element (it would be right before EOF), or in a typed array (its items are essentially bit patterns, not CE objects).

There are a couple exceptions to this, however.  You can put a comment before an end-of-container marker, like `[3 4 5 /* done */]`.  You can put multiple comments in a row (which I assume isn't meant to imply a meta-comment).  I don't necessarily think these should be changed, because they could be useful.  If the documentation were being clarified, though, they could be mentioned as exceptions to a "comments must appear right before CE objects (which they refer to)" rule.

**Comment by kstenerud** [comment]
This part of the example is wrong:

```
    "data" // Comment after data
    =
```
There can be no comment after the data. I'll update the example to match what's on the website.

The problem with where comments can exist comes from the dual binary/text formats; CBE is byte-oriented, and so there's a single "comment begin" type and a single "comment end"  type. This means that a comment operates internally like a container (basically a list with restricted contents), and can therefore only be placed where a full object can be placed.

So for the example above which I forgot to update a long time ago `{ a /* xyz */ = b }` can't be represented in CBE because CBE has no concept of "="; it just alternates key/value/key/value with some exceptions for pseudo-objects. In this case it would see the events `[map begin]`, `[string a]`, `[comment begin]`, `[string xyz]`, `[container end]`, `[string b]`, `[container end]`, which when translated back to CTE become `{ a = /* xyz */ b }`. There's no way to tell it that the comment should occur *before* the "=". But of course this is getting into the nitty gritty of the formats and this level of depth is something nobody would read...

So in the specs I tried to explain that you can put pseudo-objects wherever a real object can be, and a series of pseudo-objects must eventually be followed by a real object, but the implications of that are subtle. Maybe I could add a bunch of examples to make it clearer?

 * `c1 { a /* x */ = b }` is not valid because no object follows the comment on the left side of the "=", and adding one would be invalid `c1 { a /* x */ y = b }`.
 * `c1 { a = /* x */ b }` is valid because a real object follows the comment. `c1 /* x */ a = b` is also valid for the same reason.
 * `c1 a /* x */` is not valid because there's no object following the last comment, and if an object were to follow, the document would be invalid due to two top-level objects a and b: `c1 a /* x */ b`.
 * `c1 /* x */ a` is valid because a real object follows the comment.
 * `c1 |u8x 11 22 33 44 /* blah */ 55 66 77|` is invalid because you can't put a full object in an array; the elements are assumed to all be of the same type (unsigned 8-bit integer).

etc...

**Comment by kstenerud** [comment]
After all the comment changes, I now have a proper (and passing) test of the [comments example](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#comment) here: https://github.com/kstenerud/go-concise-encoding/blob/master/tests/ce-specification-examples.cte#L848

All CTE examples can now also be verified using the [snippet check tool](https://github.com/kstenerud/go-concise-encoding/tree/master/tests/snippet_check)
