### ISSUE TITLE
Comment characters appearing in comments

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#24]
I assume that escaping comment delimiters within a comment makes them parse as ordinary characters, not nested comments, and that when writing such characters, they must be escaped.

Either way, though, there's something fishy going on here:

```
$ echo 'c1 [1 // foo */ bar
2]' | ./enctool convert -df cte
c0
[
    1
    /* foo */ bar */
    2
]
```

Applied once, enctool will parse this and write it out, but if you try to parse enctool's output with enctool again, it fails.

**Comment by kstenerud** [comment]
Yes, this happens because the encoder always chooses the multiline comment encoding, which breaks if you've deliberately encoded `*/` within a single-line comment.

I'll probably make the encoder a little more clever such that it attempts to choose single-line comments when reasonable, but in the end there will have to be a give-up point to avoid excessive memory/CPU usage, so there will always be input that can be crafted to fail. Fortunately, the binary format doesn't have this problem, and it is the canonical format. It just means that you could in theory craft data such that if it were transformed into CTE and then attempted to transform back, it would fail parsing (not the end of the world).

No matter what, multiline comments will always have an Achilles heel, regardless of whether nested comments are allowed or not. Only single-line comments can be 100% safe (but they make block commenting difficult without IDE support).

**Comment by kengruven** [comment]
> which breaks if you've deliberately encoded */ within a single-line comment

Hmm.  It's technically a bug in the parser, right?  The CE structural spec says the `/*` and `*/` character sequences "MUST NOT be put into comment strings".  When the CTE reader is sees `//`, I think it should read until end-of-line, and if it ever sees the two-byte sequence `/*` or `*/`, I would expect that to be a structural error.

I do see that the CTE spec says within a `//` comment, "No checks for nested comments are performed", but I wouldn't expect that to override the structural rules, i.e., I take this to mean that you can't make a nested comment using another `//` (or a `/*`), but the ban on `/*` and `*/` in string content is still in effect.

(BTW: CTE generally allows either LF or CRLF for end-of-line, but for comments, it specifically says single-line comments are `//` until U+000a [LF] only, which is strange.  CR isn't considered "collapsible", so this will make a difference when parsing CRLF files.)

> you could in theory craft data such that if it were transformed into CTE and then attempted to transform back, it would fail parsing (not the end of the world).

Not the end of the world, but it was one of the selling points of the twin formats.  Until we've got native CBE editors, I think that having a CBE file that can't be disassembled back into CTE at all is a significant limitation.

Generally, with (programming) languages that support single- and multi-line comments, you can "escape" one inside the other.  It's not *exactly* the same because compilers just throw away comments, so whether `\/\*` inside a comment is technically considered equivalent to the 2-character string `/*` (versus the 4-character string `\/\*`) is never really discussed.

I don't think it's as simple as saying "comments should support all standard escapes", because I'm not sure that I want`// 1 \n 2` to parse like `/* 1 */ 2`.  But I also think that being able to encode any Unicode string in a comment (in either CTE/CBE), and read/write them efficiently, is a valuable feature.

**Comment by kstenerud** [comment]
Ugh this is becoming a pain...

Given the following:

    {
        "v1" = 1
        /*
        "v2" = 2
        "v3" = 3
        */
    }

With text editor support, commenting out some lines with CMD-/ might look like this:

    {
    //  "v1" = 1
    //  /*
    //  "v2" = 2
        "v3" = 3
    //  */
    }

If the CTE encoder were to read this, properly trim excess whitespace, AND always output in single-line comment format, it would look like this:

    {
        // "v1" = 1
        // /*
        // "v2" = 2
        "v3" = 3
        // */
    }

This is technically fine since a decoder handling a single-line comment is not supposed to interpret comment initiators or terminators; only EOL.

However, if the CTE encoder decides to output in multiline comment format, we have a problem:

    {
        /* "v1" = 1 */
        /* /* */
        /* "v2" = 2 */
        "v3" = 3
        /* */ */
    }

And even with no comments at all, we have problems:

    {
        "comment-start" = "/*"
        "comment-end" = "*/"
        "list-start" = "["
        "list-end" = "]"
    }

This is fine:

    {
        "comment-start" = "/*"
        // "comment-end" = "*/"
        // "list-start" = "["
        // "list-end" = "]"
    }

This is not:

    {
        "comment-start" = "/*"
        /*
        "comment-end" = "*/"
        "list-start" = "["
        "list-end" = "]"
        */
    }

And if we start allowing escapes inside of comments, then we run into trouble here:

    {
    /*
        "str" = "\/\*"
    */
    }

Ultimately, the problem exists because inside of comments the parser has to throw out all context that existed (or perhaps never existed) before enclosing in comments, and that means that there will ALWAYS be text sequences that break things when uncommented if you allow some sequences to have special meaning, such as `/*`, `*/`, escapes, etc.

This is why many languages do away with multiline comments altogether. Technically speaking, with proper text editor support you can still block comment/uncomment with minimal fuss, and you avoid all of these problems rather neatly. The moment you allow multiline comments, you open the door to parsing issues whether you allow nested comments or not.

Right now the reference encoder is hardwired to always output in multiline format, which is why these issues are surfacing. Technically speaking, the more trivial issues can be solved by just making the encoder smart enough to output `//` when a comment consists of only [COMMENT START] [STRING-WITH-NO-LF] [END]. But the more complex failure cases will still remain.

But that might just be enough. The languages that allow multiline comments seem to do okay despite having these exact same problems. Or maybe I should remove multiline comments altogether to make it simpler to implement?

**Comment by kengruven** [comment]
I don't think I'm ready to suggest a course of action yet.  I'm still trying to understand the problem space.

Would it be correct to say that one of the root causes of this problem is that the reader throws away a piece of useful information (the CTE comment type), so the writer has to try to guess what it was?  Would this be a non-issue if (hypothetically) CBE encoded comments with an extra bit that signified the type of comment?

**Comment by kstenerud** [comment]
The immediate problem is that the encoder doesn't yet have the smarts to generate a `//` style comment (it always uses `/* */`). An extra encoding to differentiate the two comment styles would work, however I think with a little cleverness a codec can figure out what kind of comment to output based on the information it already has:

* If there is only one entry in the comment container, and it's a string that doesn't contain linefeeds, use `//`
* Otherwise, use `/* */`

This would of course cause it to round-trip convert `/* a comment */` to `// a comment`, but that's probably not a terrible thing.

If we're to consider deliberately bad data, then in theory someone could build a CBE document containing a multiline comment or nested comment that has the string sequence `*/` in it. The codec would have to check for those kinds of shenanigans and reject the document.

With that change CE would be on par with every other technology that supports `/* */` style comments, having the same strengths, weaknesses, and edge cases (like the ones I listed above).

**Comment by kstenerud** [comment]
Trying to brainstorm the pros/cons of multiline comments...

### Multiline Comments

**Pros**:

* Block commenting is easy even if your text editor doesn't have CTE support.

**Cons**:

* Complicated to implement.
* Has unfixable edge cases that can break parsing.
* Difficult-to-impossible to maintain alignment of multiline comments if the indentation levels change when converting binary/text.

### Single-line comments only

**Pros**:

* Extremely simple to implement.
* Comment contents cannot break parsing.
* Impossible to have edge cases or false positives
* One less container type (comment will internally be a string-like type)
* Commenting of comments works just fine without any complicated machinery to support it.

**Cons**:

* Block commenting works only if your editor has CTE support.

Is block commenting in a non-supported text editor the only benefit of multiline comments? What else is there?

If that's literally the ONLY benefit, it's probably better to just drop them and lose the complications.

**Comment by kengruven** [comment]
I still don't know what the right answer is.

Right now, CE comments seem to be a combination of different types of comments.  It's not as strict as "one comment per value", but it's not as lenient as "comment anywhere".

I guess what I'm having trouble grasping about CE comments is that it's not clear to me what the use case is, or exactly what the semantic meaning is.
 - An application which happens to use the CBE format behind the scenes (and thus should allow any text)?  A utility which uses the CTE format as a user interface (where the user is expected to understand its limitations, and nesting/quoting)?  A structured data file (which can be anything the user wants)?  A wire protocol (which hopefully won't use comments at all)?
 - With a text editor which has a CTE mode?  With a text editor using its C language mode?  With a text editor which has no language editing modes at all?  (You mention "even if your text editor doesn't have CTE support", but it should still be easy in any *programming* editor even without dedicated CTE support, so I don't see that as an issue unless you want to support all the way down to editors like Notepad -- and all of CTE's features will be awkward there, not just comments.)
 - As a way to attach a comment to a specific value?  As a way to add comments between or around values?  As a way to add comments as lines/blocks to sections of the file?  (There's *one* place in a CTE map that you can't put a comment, and I can't ever remember what it is without trying it in `enctool` and seeing if it fails.)  [Comments after keys are verboten, but comments after values are fine.]

For example, let's say I write a hot new application, and use CE as the config file format.  The user can open ~/.foorc and add a comment to the file (a great improvement over JSON).  Or the user can choose the "Preferences..." menu item to edit the settings without ever seeing CE.  Can the application show saved comments for the respective settings?  Can it allow editing them?  I'm not sure.

Without CE multiline comments, this is harder.  The user could add a "block comment" (several lines of single-line comments) to a CE file but that's really just punting the responsibility for parsing "a block" over to the application.

Another advantage of "multiline comments": they're also part-of-a-line comments.  If you only have `//` available, with a line like `["a", "b", "c", "d", "e"]`, to comment out `"c",`, you need to add 2 extra newlines first.

Of course, there are many other types of comments, and even if "disabling part of a line" is a goal, `/* */` isn't the only way to accomplish this task.  For example, Clojure has a reader macro `#_` which ignores the next value, so you could say `["a", "b", #_"c", "d", "e"]` to temporarily remove one item.  That may or may not be useful here -- to remove N items is O(N) edits, using this feature, rather than O(1) edits using `/* */`.

Speaking of edit size, commenting out an entire section of a file with `/* */` also doesn't mess up the history of the file.  Even if Emacs makes it trivial to add `//` to 1000 lines, now I've got a 1000-line diff.  It's not uncommon for me to comment out something, and keep maintaining that disabled content for a future where I may want to re-enable it.  Multiline comments would help here.

Another approach: Raku allows using any matched delimiters for comments, or even multiples (like `<` `>` or `{{` `}}`).  That's helpful with being able to avoid escaping/quoting characters in comments, because you can just pick a different delimiter than the one you want to use in your comment.  But there's a finite set, so this might not be as useful for people writing serializers that must handle the general case.

Another option might be to allow "nested comments" but only as a feature of CTE syntax, not a structural one, i.e., `/* a /* b */ c */` parses as the comment string `a /* b */ c`, not a tree structure.  (I see value in "nested comments" but I'm not yet sold on encoding that in binary.)  Does this make anything easier?  I haven't fully thought through the consequences of this.

**Comment by kstenerud** [comment]
Hmm... Actually you have a point there... When would anyone need to preserve comments in a CBE document? CBE exists for machine ingestion to keep things small and fast, and comments are only bloat in the end. Machines won't care about the comments anyway.

If a "canonical" data file is needed, it will probably be in CTE since it will be edited by humans, and then a CBE version created after each edit for machines to use. Compiled code doesn't preserve comments for the same reason.

With this in mind, it's probably best to *not* have comment support in CBE at all (same as with constants). Then most of the other problems and weird rules just melt away.

**Comment by kengruven** [comment]
That wasn't my intended suggestion but that's certainly a possible direction to take it!

I suppose that makes sense.  I've been thinking of CTE/CBE as two encodings of an identical structure, but it's already more like source/object code.  "Compiling" CTE to CBE already loses information, like numeric types and sizes (a.k.a., type erasure), and string formatting/escaping (verbatim sections, etc).

I agree that removing comments from the structural spec (and into CTE only) would make it a lot simpler.  Could this allow some of the other restrictions on comments to be relaxed, like their position rules, and whitespace requirements?

I suppose for my use cases, I'd have to declare the user-facing file is "CTE" rather than "CE", and make the promise that I won't delete the user's comments if the application edits the file automatically.

**Comment by kstenerud** [comment]
Here's the current draft for the structural spec:

### Comment

A comment is a string-like pseudo-object that is invisible for the purposes of document structure (i.e. it cannot act as a real object). Comments are only available in CTE documents. Its only purpose is to add extra information for human readers. CBE encoders **CANNOT** encode comments.

CTE supports two forms of comments:

 * Single-line comments, which end at the line end (`// a comment`).
 * Multi-line comments, which can span multiple lines of text, and support nesting (`/* a comment */`).

Comments **MUST ONLY** contain [text-safe](#text-safety) characters.

Comments are allowed anywhere in a CTE document except:

 * Before the [version specifier](#version-specifier) (`/*comment*/c1` is invalid)
 * Inside of a string-like array type (strings, resource IDs, custom text) (`"/*comment*/"` would be interpreted as a string)
 * After the top-level object (`c1 100 /*comment*/` is invalid)
 * Between left and right side of a [combined object](#combined-objects) (`na:/*comment*/"IO Error"` and `@"http://x.com/"/*comment*/:"blah` are invalid)

---------------------------------
And the CTE spec:

### Comment

Comments **CAN** be written in single-line or multi-line form, and do not process escape sequences.

#### Single Line Comment

A single line comment begins at the sequence `//` and continues until the next linefeed (u+000a) is encountered. No checks for nested comments are performed.

#### Multiline Comment

A multiline comment begins at the sequence `/*` and is terminated by the sequence `*/`. Multiline comments support nesting, meaning that further `/*` sequences inside the comment will start subcomments that **MUST** also be terminated by their own `*/` sequence. No processing of the comment contents other than detecting comment begin and comment end is peformed.

**Note**: Commenting out strings or markup contents containing the sequences `/*` or `*/` could potentially cause parse errors because the parser won't have any contextual information about the sequences, and will simply treat them as "comment begin" and "comment end". This edge case could be mitigated by pre-emptively escaping all occurrences of `/*` and `*/` in string-like objects:

```cte
c1
{
    // Pre-emptively escape the "*" to avoid a false nested comment begin
    "comment begin" = "/\*"

    // Pre-emptively escape the "/" to avoid a false nested comment end
    "comment end" = "*\/"
}
```

**Comment by kstenerud** [comment]
Comments are now CTE only, and are simply treated as a string of characters. The contents no longer matter except for detecting nesting in the comments (and being text safe, like everything else in CTE). Comments are no longer container-like, meaning the ENTIRE comment structure (including sub-comments along with their /* and */ delimiters) is just treated like a giant UTF-8 blob in the reference implementation. How a particular implementation deals with this is up to the developer so long as they can regenerate a valid CTE document with the same comment contents, but I've found that this is the simplest approach.
