### ISSUE TITLE
@na payload parsing

### ISSUE THREAD

**Issue by kengruven** [kstenerud/enctool#6]
The CE spec for `@na` says: "The second NA in this special case doesn't itself require another reason field."

Doesn't require, or doesn't allow?

Currently, enctool parses `c1 [@na:@na:5]` as `c1 [@na 5]`, which is a rather different structure.

Given how CBE is defined, that's not entirely surprising.  Converting this CTE to CBE gives bytes 7e 7e 05, and there's no way for CBE to encode that the 05 is part of the second 7e, rather than a standalone integer.  It's a little odd that the second ":" is not an error in the CTE parser, in that case, though.

It looks like you should be able to write `@na:@na:5` using a marker/reference:

```
c1 [
    &1:@na:5
    @na:$1
]
```

but trying to parse this gives error "Reference To Resource ID Rule does not allow PositiveInt".

----

How do I expect `@na` payloads to work?  I like that the null value has a "reason" attached, and that it can be almost any value.  Obviously there needs to be *some* base case.  And I don't really want to add further restrictions on it (e.g., "The reason can't be another `@na`"), though I suppose that's an option.

Personally, I think the most natural solution would be to simply say that the reason is always optional.  In CTE, then, `@na` would be the base case, not "shorthand" for `@na:@na`.  `@na:@na:5` would be allowed, both directly and via reference.  In that case, `@na:@na` would still be valid CTE (though a little silly).

You'd need to tweak CBE, but there are ways to do that without adding to the encoded length.  For example, you could define it as: first 7e, and then either a reason value, or 7b to omit a reason.  Plain `@na` would still be only 2 bytes (now 7e 7b), and `@na` with a reason payload would be exactly the same as now.

**Comment by kstenerud** [comment]
Yes, this definition could use some tightening up. The idea is that the first NA means "not available", and the reason can also be "not available", but you can't chain a bunch of them together as in "not available for reason not available for reason not available for reason not available...".

**Comment by kstenerud** [comment]
Alright, I've tightened up [the spec](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#na), and the latest library now properly catches things like `@na:@na:5`. The second `:` triggers concatenation so you'll see an error of `TODO: decodeSuffix` since that's not implemented yet, but once it is, the concatenation operation is only valid on resource IDs anyway, so this case will properly generate an error diagnostic.

**Comment by kengruven** [comment]
Thanks.  I'll test this later.

I'm still having trouble with the syntax `@na:@na`.  The two `@na` here look identical but have different meanings.  One is a container (essentially an option type like Maybe) which holds a reason.  The other is an atom which signifies "no reason given" (essentially a None value), which can only occur in this specific context.

It's another special case for implementors of CE to deal with, and another special case for users of CTE to learn.  Why not just specify that an NA's "reason" payload is optional, so `@na` is the plain version, and forbid `@na:@na`?

I could understand keeping a longer equivalent syntax for reasons of consistency, but for CTE NA values, the longer version is also a special case, both internally and externally.

**Comment by kstenerud** [comment]
Hmm perhaps this could do with a re-think...

My original design was centered on the CBE encoding, such that NA (0x7e) must be followed by a second object that would serve as its reason, with a second NA (0x7e) type signaling "no reason given". NA-NA (0x7e, 0x7e) was a convenient way to encode that information in CBE, but the reasoning isn't at all clear when applied to CTE.

If I were to instead focus on CTE first and CBE second, this looks more like another form of concatenation (`:`). In this model, NA would be its own object, and one can optionally append an object to it via the contatenation operator, which would serve as its reason. Now, NA with no reason given is `@na` for CTE and 0x7e for CBE. Adding reason "because" would look like `@na:because` for CTE and `[7e 96 87 62 65 63 61 75 73 65]` for CBE (where `7e` = NA, `96` = concatenate, `87` = 7-byte string).

And since NA is not a common type, an extra byte to encode NA-with-reason will have a negligible impact on payload size.

Now with this design, the left-side of the concatenate operation can be NA or resource ID, and the left-side type determines what types are valid on the right-side (resource ID supports string or numeric like before, and NA will probably support most real types...). All other concatenate rules would apply the same as before.

**Comment by kstenerud** [comment]
Alright, after more thought this makes sense and is a lot cleaner. NA's reason field is now implemented as a [concatenation](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#concatenation) so that it looks and behaves similarly to [concatenated resource IDs](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#resource-identifier).

In CTE it looks like [this](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#concatenation), and in CBE it looks like [this](https://github.com/kstenerud/concise-encoding/blob/master/cbe-specification.md#concatenation).

I've also moved the concatenation operation in CBE to a parallel type in the [2nd type plane](https://github.com/kstenerud/concise-encoding/blob/master/cbe-specification.md#type-field-plane-2) (formerly the array type plane) because encoding it as an optional suffix type broke deterministic document endings (how does one know after `[03 01 7e]` that we're really at the end of the document without peeking at the next byte to see if it's a concatenation operator?). The cool thing is that it still encodes in the same number of bytes using the new way, plus there's now another free type in the 1st plane :)

Next is updating the go reference implementation...

**Comment by kengruven** [comment]
I haven't gotten to Concatenation yet, so I'll trust that it all makes sense.  This does simplify the `@na:@na` situation, so I'm happy with that.  It looks fine in CTE, and I'm not concerned with what bytes are used for CBE.

The original document, above, is now invalid:

```
c1 [
    &1:@na:5
    @na:$1
]
```

This now gives: "TODO: decodeSuffix", but I'm sure you knew that already.

**Comment by kstenerud** [comment]
Yup, the library hasn't been updated yet; only the spec. None of the concatenation functionality is implemented in the reference library yet.

References won't be allowed as NA reasons in order to keep the format from becoming too complicated. Concatenation will be very limited as a general principle because operators have a tendency to complicate things very fast, and I'd rather focus on real-world utility for specific use cases over expressivity when complication is the price.

**Comment by kengruven** [comment]
I think `na` works as specced now, so I'm closing this.
